version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: shareit-postgres
    environment:
      POSTGRES_DB: shareit
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build: server
    image: shareit-server
    container_name: shareit-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/shareit
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "9090:9090"
    depends_on:
      postgres:
        condition: service_healthy

  gateway:
    build: ./shareit-gateway
    container_name: shareit-gateway
    environment:
      SHAREIT_SERVER_URL: http://shareit-server:9090
    ports:
      - "8080:8080"
    depends_on:
      - shareit-server

volumes:
  postgres_data: